In [1]:
import pandas as pd
import numpy as np

In [42]:
df = pd.read_csv('train.csv', index_col='Id')
df.head()

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
Id                                                               
1        2596      51      3                               258   
2        2590      56      2                               212   
3        2804     139      9                               268   
4        2785     155     18                               242   
5        2595      45      2                               153   

    Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
Id                                                                    
1                                0                              510   
2                               -6                              390   
3                               65                             3180   
4                              118                             3090   
5                               -1                              391   

    Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
Id                                                 
1             221             232            148   
2             220             235            151   
3             234             238            135   
4             238             238            122   
5             220             234            150   

    Horizontal_Distance_To_Fire_Points  ...  Soil_Type32  Soil_Type33  \
Id                                      ...                             
1                                 6279  ...            0            0   
2                                 6225  ...            0            0   
3                                 6121  ...            0            0   
4                                 6211  ...            0            0   
5                                 6172  ...            0            0   

    Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  Soil_Type38  \
Id                                                                    
1             0            0            0            0            0   
2             0            0            0            0            0   
3             0            0            0            0            0   
4             0            0            0            0            0   
5             0            0            0            0            0   

    Soil_Type39  Soil_Type40  Cover_Type  
Id                                        
1             0            0           5  
2             0            0           5  
3             0            0           2  
4             0            0           2  
5             0            0           5  

[5 rows x 55 columns]

time: 129 ms


In [3]:
df.isnull().any().any()

False

In [43]:
df.describe()

Elevation        Aspect         Slope  \
count  15120.000000  15120.000000  15120.000000   
mean    2749.322553    156.676653     16.501587   
std      417.678187    110.085801      8.453927   
min     1863.000000      0.000000      0.000000   
25%     2376.000000     65.000000     10.000000   
50%     2752.000000    126.000000     15.000000   
75%     3104.000000    261.000000     22.000000   
max     3849.000000    360.000000     52.000000   

       Horizontal_Distance_To_Hydrology  Vertical_Distance_To_Hydrology  \
count                      15120.000000                    15120.000000   
mean                         227.195701                       51.076521   
std                          210.075296                       61.239406   
min                            0.000000                     -146.000000   
25%                           67.000000                        5.000000   
50%                          180.000000                       32.000000   
75%                          330.000000                       79.000000   
max                         1343.000000                      554.000000   

       Horizontal_Distance_To_Roadways  Hillshade_9am  Hillshade_Noon  \
count                     15120.000000   15120.000000    15120.000000   
mean                       1714.023214     212.704299      218.965608   
std                        1325.066358      30.561287       22.801966   
min                           0.000000       0.000000       99.000000   
25%                         764.000000     196.000000      207.000000   
50%                        1316.000000     220.000000      223.000000   
75%                        2270.000000     235.000000      235.000000   
max                        6890.000000     254.000000      254.000000   

       Hillshade_3pm  Horizontal_Distance_To_Fire_Points  ...   Soil_Type32  \
count   15120.000000                        15120.000000  ...  15120.000000   
mean      135.091997                         1511.147288  ...      0.045635   
std        45.895189                         1099.936493  ...      0.208699   
min         0.000000                            0.000000  ...      0.000000   
25%       106.000000                          730.000000  ...      0.000000   
50%       138.000000                         1256.000000  ...      0.000000   
75%       167.000000                         1988.250000  ...      0.000000   
max       248.000000                         6993.000000  ...      1.000000   

        Soil_Type33   Soil_Type34   Soil_Type35   Soil_Type36   Soil_Type37  \
count  15120.000000  15120.000000  15120.000000  15120.000000  15120.000000   
mean       0.040741      0.001455      0.006746      0.000661      0.002249   
std        0.197696      0.038118      0.081859      0.025710      0.047368   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

        Soil_Type38   Soil_Type39   Soil_Type40    Cover_Type  
count  15120.000000  15120.000000  15120.000000  15120.000000  
mean       0.048148      0.043452      0.030357      4.000000  
std        0.214086      0.203880      0.171574      2.000066  
min        0.000000      0.000000      0.000000      1.000000  
25%        0.000000      0.000000      0.000000      2.000000  
50%        0.000000      0.000000      0.000000      4.000000  
75%        0.000000      0.000000      0.000000      6.000000  
max        1.000000      1.000000      1.000000      7.000000  

[8 rows x 55 columns]

time: 402 ms


In [56]:
X, y = df.drop('Cover_Type', axis=1), df[['Cover_Type']]
from sklearn.model_selection import cross_val_score, GridSearchCV, train_test_split

print(X.shape)
print(y.shape)

(15120, 54)
(15120, 1)
time: 7.45 ms


In [10]:
!pip install ipython-autotime

  Stored in directory: /Users/mihas/Library/Caches/pip/wheels/d2/df/81/2db1e54bc91002cec40334629bc39cfa86dff540b304ebcd6e
Successfully built ipython-autotime


In [6]:
%load_ext autotime


time: 10.9 ms


In [ ]:
X_train, X_valid, y_train, y_valid = train_test_split(X,y, train_size=0.8)

print(X_train.shape)
print(X_valid.shape)
print(y_train.shape)
print(y_valid.shape)

from xgboost import XGBClassifier
# model = XGBClassifier(
#     booster='gbtree',
#     n_jobs=-1, n_estimators=1000, learning_rate=0.01, max_depth=3
# )
# model = XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
#               colsample_bynode=1, colsample_bytree=1, gamma=0,
#               learning_rate=0.1, max_delta_step=0, max_depth=3,
#               min_child_weight=1, missing=None, n_estimators=2048, n_jobs=-1,
#               nthread=None, objective='multi:softprob', random_state=0,
#               reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
#               silent=None, subsample=1, verbosity=1)
# eval_set = [
#     (X_train, y_train)
# #     , (X_valid, y_valid)
# ]
model = XGBClassifier(
    n_jobs=-1,
    learning_rate= 0.1,
    n_estimators=100,
    max_depth= 9,
#     subsample= 1,
#     colsample_bytree=1,
#     gamma=0
)

clf = GridSearchCV(estimator=model, 
                   param_grid=dict(
                       gamma=[0, 1, 5],
                       colsample_bytree=[0.3, 0.5, 0.8, 1],
                       subsample=[0.5, 0.8, 1]
                   ),
                   verbose=10,
                   n_jobs=-1,

 
                  )
#eval_metric="merror"
# eval_set = [(X_valid, y_valid)]
# model.fit(X_train, y_train, verbose=True,
#                 eval_metric=eval_metric, 
#                 eval_set=eval_set,
# )


# model.score(X_valid, y_valid,)

clf.fit(X_train, y_train,verbose=True,)
clf.score(X_valid, y_valid,)


(12096, 54)
(3024, 54)
(12096, 1)
(3024, 1)
Fitting 3 folds for each of 36 candidates, totalling 108 fits


/Users/mihas/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:   27.3s
[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:   57.8s
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:  2.6min
[Parallel(n_jobs=-1)]: Done  45 tasks      | elapsed:  3.4min


In [87]:
clf.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=9,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=-1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=0.8, verbosity=1)

time: 2.98 ms


In [88]:
clf.best_score_

0.8450727513227513

time: 1.88 ms


In [61]:

from xgboost import XGBClassifier

model = XGBClassifier(n_jobs=-1, n_estimators=100, learning_rate=0.001, max_depth=10)

cross_val_score(model, X,y, cv=3, scoring='accuracy', n_jobs=-1,
#                fit_params={'early_stopping_rounds':1}
               )


array([0.72400794, 0.69880952, 0.72698413])

time: 52.8 s


In [19]:
from sklearn import svm 
model = svm.SVC(kernel='linear', C=1)
cross_val_score(model, X,y, cv=3, scoring='accuracy', n_jobs=-1,
#                fit_params={'early_stopping_rounds':1}
               )

KeyboardInterrupt: 

time: 15min 58s


In [7]:
np.logspace(-4, -1, 4)

array([0.0001, 0.001 , 0.01  , 0.1   ])

In [13]:
model = XGBClassifier(n_jobs=-1)
clf = GridSearchCV(estimator=model, 
                   param_grid=dict(
                       n_estimators=[128,512, 1024, 2048],
                       learning_rate=np.logspace(-4, -1, 4, base=10)
                   ),
                   verbose=2
                  )
X_test, X_valid, y_test, y_valid = train_test_split(X,y, train_size=0.8)
clf.fit(X_test, y_test)
cross_val_score(model, X,y, cv=5, scoring='accuracy', n_jobs=-1,)

/Users/mihas/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


KeyboardInterrupt: 

In [10]:
# clf.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=2048, n_jobs=-1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [17]:
# clf.cv_results_

{'mean_fit_time': array([ 4.41403397, 17.41647243, 35.34805695, 70.45469022,  4.42378434,
        17.60965721, 35.80288831, 70.87326368,  4.47302222, 17.7299583 ,
        35.22208349, 70.04959083,  4.40288814, 17.3657883 , 34.68051815,
        70.04119984]),
 'std_fit_time': array([0.01422819, 0.02383881, 0.59046023, 0.35910974, 0.02457988,
        0.0732541 , 0.69990114, 0.68203568, 0.03847747, 0.05169759,
        0.05799536, 0.59324889, 0.02923007, 0.03235285, 0.19938421,
        0.28559983]),
 'mean_score_time': array([0.06513604, 0.34126902, 0.74505536, 1.55250796, 0.0676326 ,
        0.34214036, 0.7460374 , 1.48314691, 0.07340018, 0.34169046,
        0.75128587, 1.63129671, 0.06455946, 0.39792919, 0.85371582,
        1.67762319]),
 'std_score_time': array([0.00082362, 0.01104186, 0.02277039, 0.04257988, 0.00284253,
        0.0099156 , 0.01043848, 0.01525416, 0.00680257, 0.00176725,
        0.01114197, 0.03806513, 0.00076419, 0.01513829, 0.0043045 ,
        0.04404282]),
 'param_le

In [16]:
best_est = XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=2048, n_jobs=-1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [15]:
# cross_val_score(clf.best_estimator_, X,y, cv=5, scoring='accuracy', n_jobs=-1,)


array([0.75562169, 0.74140212, 0.75165344, 0.76587302, 0.83201058])

In [18]:
best_est.fit(X,y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=2048, n_jobs=-1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [19]:
X_test = pd.read_csv('/kaggle/input/learn-together/test.csv', index_col='Id')

In [21]:
X_test.isnull().any().any()

False

In [22]:
y_test = best_est.predict(X_test)
y_test

array([1, 1, 1, ..., 3, 3, 3])

In [35]:
s_df = pd.DataFrame({'ID': X_test.index, 'Cover_Type': y_test})
s_df

ID  Cover_Type
0        15121           1
1        15122           1
2        15123           1
3        15124           5
4        15125           5
...        ...         ...
565887  581008           3
565888  581009           3
565889  581010           3
565890  581011           3
565891  581012           3

[565892 rows x 2 columns]

In [27]:
s_df.to_csv('submission.csv', index=False)

/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 